return {
  "AstroNvim/astrocommunity",
  { import = "astrocommunity.pack.lua" },
  { import = "astrocommunity.pack.typescript" },
  { import = "astrocommunity.pack.go" },
  { import = "astrocommunity.pack.docker" },
  { import = "astrocommunity.pack.nvchad-ui" },
  { import = "astrocommunity.pack.tailwindcss" },
  { import = "astrocommunity.pack.yaml" },
  { import = "astrocommunity.pack.json" },
  { import = "astrocommunity.completion.copilot-lua-cmp" },
  -- import/override with your plugins folder
  { import = "astrocommunity.colorscheme.catppuccin" },
  { import = "astrocommunity.colorscheme.tokyodark-nvim" },
  { import = "astrocommunity.colorscheme.tokyonight-nvim" },
  { import = "astrocommunity.colorscheme.vscode-nvim" },
  { import = "astrocommunity.colorscheme.palenight-nvim" },
  -- { import = "astrocommunity.color.nvim-highlight-colors" },
  -- { import = "astrocommunity.snippet.nvim-snippets" },
  -- { import = "astrocommunity.code-runner.compiler-nvim" },
  -- { import = "astrocommunity.color.huez-nvim" },
  -- { import = "astrocommunity.code-runner.executor-nvim" },
  -- { import = "astrocommunity.git.neogit" },
  -- { import = "astrocommunity.recipes.vscode-icons" },
  -- { import = "astrocommunity.recipes.telescope-nvchad-theme" },
}
